{% set name = "firewxpy" %}
{% set version = "1.0.0.73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firewxpy-{{ version }}.tar.gz
  sha256: 53ddf5014c8b7283922a5775891e435f5a4d2e2e8efa2f234b6e0dd47871f458

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.7
    - protobuf ==3.20.3
    - metpy >=1.5.1
    - netcdf4 >=1.7.1
    - numpy >=1.24
    - pandas >=2
    - siphon >=0.9
    - xarray >=2023.1.0
    - pysolar >=0.11
    - pygrib >=2.1.4
    - cfgrib >=0.9.10.4
    - cartopy >=0.21.0
    - imageio >=2.34.0

test:
  imports:
    - firewxpy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Weather Analysis and Forecasting For Fire Weather
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - edrewitz
