[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FireWxPy"
version = "1.00"
authors = [
  { name="Eric J Drewitz, USDA/USFS"},
]
description = "Weather Analysis and Forecasting For Fire Weather"
readme = "README.md"
keywords = ["meteorology", "science", "data-analysis", "weather", "forecasting"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
	"matplotlib>=3.8.0",
	"metpy>=1.5.1",
	"netcdf4>=1.6.3",
	"numpy>=1.26.2",
	"pandas>=2.1.4",
	"siphon>=0.9",
	"scipy>= 1.10.1",
	"xarray>=2023.12.0",
]
